// <auto-generated />
using System;
using CrossRef.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrossRef.Migrations
{
    [DbContext(typeof(CrossRefContext))]
    partial class CrossRefContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("CrossRef.Common.Data.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DOI");

                    b.Property<DateTime?>("Published");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.Property<string>("Url");

                    b.Property<int>("YearOfPublication");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("CrossRef.Common.Data.Entities.ArticleAuthors", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("ArticleId");

                    b.Property<int>("Id");

                    b.HasKey("UserId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleAuthors");
                });

            modelBuilder.Entity("CrossRef.Common.Data.Entities.Collaborator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthorId");

                    b.Property<int?>("AuthorUserId");

                    b.Property<int>("CollaboratorId");

                    b.Property<int?>("CollaboratorUserId");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("CollaboratorUserId");

                    b.ToTable("Collaborators");
                });

            modelBuilder.Entity("CrossRef.Common.Data.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthorId");

                    b.Property<bool>("ShowAffiliation");

                    b.Property<bool>("ShowArticles");

                    b.Property<bool>("ShowBiography");

                    b.Property<bool>("ShowDateOfBirth");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("CrossRef.Common.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Affiliation");

                    b.Property<string>("Biography");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CrossRef.Common.Data.Entities.ArticleAuthors", b =>
                {
                    b.HasOne("CrossRef.Common.Data.Entities.Article", "Article")
                        .WithMany("ArticleAuthors")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CrossRef.Common.Data.Entities.User", "User")
                        .WithMany("ArticleAuthors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CrossRef.Common.Data.Entities.Collaborator", b =>
                {
                    b.HasOne("CrossRef.Common.Data.Entities.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId");

                    b.HasOne("CrossRef.Common.Data.Entities.User", "CollaboratorUser")
                        .WithMany()
                        .HasForeignKey("CollaboratorUserId");
                });

            modelBuilder.Entity("CrossRef.Common.Data.Entities.Permission", b =>
                {
                    b.HasOne("CrossRef.Common.Data.Entities.User", "Author")
                        .WithOne("Permission")
                        .HasForeignKey("CrossRef.Common.Data.Entities.Permission", "AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
